#!/bin/bash

# for simple oneliner
# yum upgrade -y | grep -q Upgraded && reboot
# apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confold 2>&1 | grep -q upgraded: && reboot

# If any of these packages is updated, we should reboot
critical_packages="kernel|libc"
# Update type
update_type=$1

# Parameters checking
echo $update_type | grep -q -i "help"
if [ $? -eq 0 ]; then
	echo
	echo "USAGE: $0 [update_type]"
	echo
	echo "where update_type can be:"
	echo "      'normal' (default)"
	echo "      'security' (security updates only)"
	echo "      'security-minimal' (minimal update to secure the system)"
	echo "      'dist-upgrade' (for debian-based systems)"
	echo
	exit 0
fi

# If not specified differently, use normal update procedure
if [ "$update_type" != "security" ] && [ "$update_type" != "security-minimal" ] && [ "$update_type" != "dist-upgrade" ]; then
	update_type="normal"
fi

# Determine OS distribution
debian=0
redhat=0
if [ -e /etc/debian_version ]; then
	debian=1
	apt-get update > /dev/null
fi

if [ -e /etc/redhat-release ]; then
	redhat=1
	yum makecache -q 2>/dev/null
	yum install yum-plugin-security -y -q 2>/dev/null
	if [ "$update_type" == "dist-upgrade" ]; then
		update_type="normal"
	fi
fi

# Check if we need to upgrade
echo "Update type selected: $update_type"
echo "Checking updates..."
if [ $redhat -gt 0 ]; then
	# Determine update type
	if [ "$update_type" == "security" ] || [ "$update_type" == "security-minimal" ]; then
		secfixes=`yum updateinfo security -q | wc -l`
		if [ $secfixes -eq 0 ]; then
			exit_code=0
		else
			exit_code=100
		fi
	else
		yum check-update > /dev/null
		exit_code=$?
	fi
	if [ $exit_code -ne 100 ]; then
		echo "No updates found"
		exit 0
	fi
fi

if [ $debian -gt 0 ]; then
	# Determine update type
	if [ "$update_type" == "security" ]; then
		pkgs=`apt-get dist-upgrade --just-print | grep "^Inst.*-security" | cut -d " " -f 2 | xargs`
	elif [ "$update_type" == "security-minimal" ]; then
		pkgs=`apt-get upgrade --just-print | grep "^Inst.*-security" | cut -d " " -f 2 | xargs`
	elif [ "$update_type" == "dist-upgrade" ]; then
		pkgs=`apt-get dist-upgrade --just-print | grep "^Inst" | cut -d " " -f 2 | xargs`
	else
		pkgs=`apt-get upgrade --just-print | grep "^Inst" | cut -d " " -f 2 | xargs`
	fi
	if [ -z "$pkgs" ]; then
		echo "No updates found"
		exit 0
	fi
fi

# Update!
echo "NOTICE: Updates found"
echo "Starting update process"
if [ $redhat -gt 0 ]; then
	if [ "$update_type" == "security" ]; then
		command="yum update --security -y"
	elif [ "$update_type" == "security-minimal" ]; then
		command="yum update-minimal --security -y"
	else
		command="yum update -y"
	fi
elif
   [ $debian -gt 0 ]; then
	export DEBIAN_FRONTEND="noninteractive"
	opts="-oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confold"
	if [ "$update_type" == "security" ]; then
		command="apt-get install -y $opts $pkgs"
	elif [ "$update_type" == "security-minimal" ]; then
		command="apt-get install -y $opts $pkgs"
	elif [ "$update_type" == "dist-upgrade" ]; then
		command="apt-get dist-upgrade -y $opts"
	else
		command="apt-get upgrade -y $opts"
	fi
fi
echo "Executing command: $command"
# Execute and error cheking
$command
update_error=$?
if [ $update_error -ne 0 ]; then
	echo "ERROR: update failed. Check the log file for details"
	exit $update_error
fi

# Debian (mostly Ubuntu) does not always automatically restart upgraded services, do it now if needrestart is available
if [ $debian -eq 1 ] && [ -e /usr/sbin/needrestart ]; then
	# Use dialog to avoid batch mode (which never restarts services) on Ubuntu 22.04
	grep -s 22.04 /etc/lsb-release && /usr/sbin/needrestart -f dialog -r a 2>&1 || /usr/sbin/needrestart -r a 2>&1
fi

# Determine if we should/can reboot
should_reboot=0
if [ $debian -eq 1 ]; then
	if [ -e /var/run/reboot-required ]; then
		should_reboot=1
	fi
fi

if [ $redhat -eq 1 ]; then
	if [ -e /usr/bin/needs-restarting ]; then
		/usr/bin/needs-restarting -r || should_reboot=1
	else
		yum history info | grep -E "$critical_packages" && should_reboot=1
	fi
fi

# If we can reboot, then REBOOT
if [ $should_reboot -gt 0 ]; then
	echo "NOTICE: we should reboot the system"
	exit 200
fi

# Exit code 100 signals an updated system
exit 100
