#!/bin/bash

# redhat only
echo "### DISTRO CHECK"
cd `dirname $0`
test -f /etc/redhat-release || echo "RedHat only support, exiting"
test -f /etc/redhat-release || exit 1

# repos
echo "### INSTALLING REPOS"
yum install -y epel-release
yum install -y https://packages.graylog2.org/repo/packages/graylog-4.3-repository_latest.rpm
cp -f ./files/*.repo /etc/yum.repos.d/
restorecon -RF /etc/yum.repos.d/
crb enable

# install
echo "### INSTALLING PACKAGES"
yum install -y pwgen java-11-openjdk-headless httpd mod_ssl mongodb-org opensearch graylog-server

# config
# /etc/opensearch/opensearch.yml
echo "### CONFIGURING PACKAGES"
grep -q "plugins.security.disabled: true" /etc/opensearch/opensearch.yml || echo "plugins.security.disabled: true" >> /etc/opensearch/opensearch.yml
# /etc/graylog/server/server.conf
password_secret=`pwgen -N 1 -s 96`
sed "s/password_secret =$/password_secret = $password_secret/" -i /etc/graylog/server/server.conf
grep -q "root_password_sha2 =$" /etc/graylog/server/server.conf && echo -n "Enter graylog password: " && root_password_sha2=`head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1`
sed "s/root_password_sha2 =$/root_password_sha2 = $root_password_sha2/" -i /etc/graylog/server/server.conf
# /etc/httpd/conf.d/graylog.conf
test -f /etc/httpd/conf.d/graylog.conf || cp -f ./files/graylog.conf /etc/httpd/conf.d/
grep -q "__EXTIP__" /etc/httpd/conf.d/graylog.conf && echo -n "Enter external IP: " && extip=`head -1 </dev/stdin | tr -d '\n'`
sed "s/__EXTIP__/$extip/" -i /etc/httpd/conf.d/graylog.conf
restorecon -RF /etc/httpd/conf.d/

# selinux and firewall
echo "### CONFIGURING SELINUX AND FIREWALL"
setsebool -P httpd_can_network_connect=on
firewall-cmd --add-port 5044/tcp
firewall-cmd --add-port 10514/tcp
firewall-cmd --add-port 10514/udp
firewall-cmd --add-port 11514/tcp
firewall-cmd --add-port 11514/udp
firewall-cmd --add-forward-port=port=514:proto=tcp:toport=10514
firewall-cmd --add-forward-port=port=514:proto=udp:toport=10514
firewall-cmd --add-service http
firewall-cmd --add-service https
firewall-cmd --runtime-to-permanent

# end
echo "### CONFIGURING AUTOSTART ON BOOT"
systemctl enable mongod
systemctl enable opensearch
systemctl enable graylog-server
echo "Finished, when ready please start in that order: mongod, opensearch and graylog-server"
exit 0
